export const EXPORT_ACTION_INIT = 'EXPORT_ACTION_INIT';
export const EXPORT_ACTION_SUCCESS = 'EXPORT_ACTION_SUCCESS';
export const EXPORT_ACTION_FAILED = 'EXPORT_ACTION_FAILED';
export const EXPORT_ACTION_CLEAR = 'EXPORT_ACTION_CLEAR';

export const DELETE_USER_INIT = 'DELETE_USER_INIT';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const BLOCK_UNBLOCK_USER_INIT = 'BLOCK_UNBLOCK_USER_INIT';
export const BLOCK_UNBLOCK_USER_SUCCESS = 'BLOCK_UNBLOCK_USER_SUCCESS';
export const BLOCK_UNBLOCK_USER_FAILED = 'BLOCK_UNBLOCK_USER_FAILED';

export const DELETE_POST_INIT = 'DELETE_POST_INIT';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';

export const BLOCK_UNBLOCK_POST_INIT = 'BLOCK_UNBLOCK_POST_INIT';
export const BLOCK_UNBLOCK_POST_SUCCESS = 'BLOCK_UNBLOCK_POST_SUCCESS';
export const BLOCK_UNBLOCK_POST_FAILED = 'BLOCK_UNBLOCK_POST_FAILED';

export const TOGGLE_USER_STATUS = 'TOGGLE_USER_STATUS';
export const TOGGLE_POST_STATUS = 'TOGGLE_POST_STATUS';

export const DELETE_MAIL_TEMPLATE_INIT ="DELETE_MAIL_TEMPLATE_INIT";
export const DELETE_MAIL_TEMPLATE_SUCCESS ="DELETE_MAIL_TEMPLATE_SUCCESS";
export const DELETE_MAIL_TEMPLATE_FAILURE ="DELETE_MAIL_TEMPLATE_FAILURE";

export const REQUEST_MANAGEMENT_ACTIONS_INIT ="REQUEST_MANAGEMENT_ACTIONS_INIT";
export const REQUEST_MANAGEMENT_ACTIONS_SUCCESS ="REQUEST_MANAGEMENT_ACTIONS_SUCCESS";
export const REQUEST_MANAGEMENT_ACTIONS_FAILURE ="REQUEST_MANAGEMENT_ACTIONS_FAILURE";
